### ISSUE TITLE
ClientError: An error occurred (AccessDeniedException) when calling the GetParameter operation

### ISSUE THREAD

**Issue by estahn** [globaldatanet/cost-reporter#11]
![image](https://user-images.githubusercontent.com/362174/109569100-01008e80-7b3c-11eb-87e1-729f70ae32e6.png)

**Comment by flyck** [comment]
Hey Enrico,

this looks like a straightforward permission issue. The SAM template gives permission to the parameter "/cost-reporter/slack-token" by default. It doesn't have permission for any other ssm parameter. Is this still the ssm parameter you're using?
